version: '2'
services:
  web:
    build: .
    restart: unless-stopped
    command: npm start
    volumes:
      - .:/usr/app/
    ports:
      - "4555:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos